
export let FORM_VOTACION = {
    titulo: 'Votacion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Votacion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Observacion',
        label_i18n: 'observacion',
        placeholder_i18n: 'observacion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Año',
        label_i18n: 'año',
        placeholder_i18n: 'año',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechaejecucion',
        label_i18n: 'fechaejecucion',
        placeholder_i18n: 'fechaejecucion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Estado',
        label_i18n: 'estado',
        placeholder_i18n: 'estado',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'DocentesPlanta',
        label_i18n: 'docentes_planta',
        placeholder_i18n: 'docentes_planta',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'DocentesVe',
        label_i18n: 'docentes_ve',
        placeholder_i18n: 'docentes_ve',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Funcionarios',
        label_i18n: 'funcionarios',
        placeholder_i18n: 'funcionarios',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Estudiantes',
        label_i18n: 'estudiantes',
        placeholder_i18n: 'estudiantes',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Egresados',
        label_i18n: 'egresados',
        placeholder_i18n: 'egresados',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Contratistas',
        label_i18n: 'contratistas',
        placeholder_i18n: 'contratistas',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Exrectores',
        label_i18n: 'exrectores',
        placeholder_i18n: 'exrectores',
        requerido: true,
        tipo: 'checkbox',
    },
    ],
}
